apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: application-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            # DB CONFIG
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-application:5432/applicationdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

            # SERVICE-TO-SERVICE COMMUNICATION
            - name: USER_SERVICE_URL
              value: http://user-service:8081

            - name: JOB_SERVICE_URL
              value: http://job-service:8082
